apiVersion: runwhen.com/v1
kind: GenerationRules
spec:
  generationRules:
  - resourceTypes:
    - resource_group
    matchRules:
    - type: pattern
      pattern: "."
      properties: [name]
      mode: substring
    slxs:
    - baseName: vm-disk-health
      levelOfDetail: basic
      qualifiers: ["resource", "resource_group", "subscription_id"]
      baseTemplateName: azure-vm-disk-health
      outputItems:
        - type: slx
        - type: sli
        - type: runbook
          templateName: azure-vm-disk-health-taskset.yaml