apiVersion: runwhen.com/v1
kind: Runbook
metadata:
  name: {{slx_name}}
  labels:
    {% include "common-labels.yaml" %}
  annotations:
    {% include "common-annotations.yaml" %}
spec: 
  location: {{default_location}}
  description: istio sidecar check
  codeBundle:
    {% if repo_url %}
    repoUrl: {{repo_url}}
    {% else %}
    repoUrl: https://github.com/runwhen-contrib/rw-cli-codecollection.git
    {% endif %}
    {% if ref %}
    ref: {{ref}}
    {% else %}
    ref: main
    {% endif %}
    pathToRobot: codebundles/istio-sidecar-check/runbook.robot
  configProvided:
    - name: CONTEXT
      value: {{context}}
    - name: KUBERNETES_DISTRIBUTION_BINARY
      value: {{custom.kubernetes_distribution_binary}}
    - name: EXCLUDED_NAMESPACES
      value: {{custom.excluded_namespaces}}
  secretsProvided:
  {% if wb_version %}
    {% include "kubernetes-auth.yaml" ignore missing %}
  {% else %}
    - name: kubeconfig
      workspaceKey: {{custom.kubeconfig_secret_name}}
  {% endif %}