apiVersion: runwhen.com/v1
kind: GenerationRules
spec:
  platform: aws
  generationRules:
    - resourceTypes:
        - ec2_instance
      matchRules:
        - type: and
          matches:
            - type: pattern
              pattern: "jenkins-server"
              properties: [tag-values]
              mode: substring
            # - type: pattern
            #   pattern: ".+"
            #   properties: [custom/jenkins_url]
            #   mode: substring

      slxs:
        - baseName: jenkins-health
          levelOfDetail: detailed
          qualifiers: ["resource"]
          baseTemplateName: jenkins-health
          outputItems:
            - type: slx
            - type: runbook
              templateName: jenkins-health-taskset.yaml
